apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-m2uu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gjug-tenant/rhtap-demo-app/hacbs-test-project-m2uu@sha256:5992212a393c98ce3b228504151c94f02b14d1f4c3593e5e5cdc6f520b63cd1d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
